apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-lbservicetype-k8s-bigip-ctlr
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      serviceAccountName: k8s-bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:2.4.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-partition=lbservicetype",
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=https://10.1.20.240:443",
            "--pool-member-type=nodeport",
            "--manage-ingress=false",
            "--manage-configmaps=false",
            "--custom-resource-mode=true",
            # "--namespace=cis-lbservicetype",
            "--namespace-label=use_cis=true",
# Some AS3 parameters for CIS config
            "--as3-validation=true",
            "--log-as3-response=true",
            "--insecure=true",
            "--override-as3-declaration=default/f5-as3-override",
            "--share-nodes=true",
# Some OpenShift parameters
            "--manage-routes=false",
            "--route-vserver-addr=10.1.10.100",
            "--route-http-vserver=ocp_http_vs",
            "--route-https-vserver=ocp_https_vs",
            "--route-label=hello-world",
            "--openshift-sdn-name=/Common/openshift_vxlan",
# Some IPAM parameters
            "--ipam=true"
           ]
